<a href="https://colab.research.google.com/github/0809lhl/CIS3120_Project-2_Web-Scraping-APIs/blob/main/project_2_Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
from urllib.parse import quote

In [25]:
url='https://en.wikipedia.org/wiki/List_of_highest-grossing_films'

In [26]:
page = requests.get(url)

In [27]:
page.status_code

200

In [28]:
soup = BeautifulSoup(page.text,'html.parser')

In [ ]:
soup

In [31]:
table = soup.find('table', {'class':'wikitable'})

In [ ]:
table

In [33]:
films = []

In [34]:
# find all table rows
for row in table.find_all('tr'):
  # get the film titles in <i> tags
  title_cell = row.find('i') # title_cell only shows rows with i tag
  if title_cell and title_cell.a:
    films.append(title_cell.get_text())

In [35]:
films

['Avatar',
 'Avengers: Endgame',
 'Avatar: The Way of Water',
 'Titanic',
 'Ne Zha 2',
 'Star Wars: The Force Awakens',
 'Avengers: Infinity War',
 'Spider-Man: No Way Home',
 'Inside Out 2',
 'Jurassic World',
 'The Lion King',
 'The Avengers',
 'Furious 7',
 'Top Gun: Maverick',
 'Frozen 2',
 'Barbie',
 'Avengers: Age of Ultron',
 'The Super Mario Bros. Movie',
 'Black Panther',
 'Harry Potter and the Deathly Hallows – Part 2',
 'Deadpool & Wolverine',
 'Star Wars: The Last Jedi',
 'Jurassic World: Fallen Kingdom',
 'Frozen',
 'Beauty and the Beast',
 'Incredibles 2',
 'The Fate of the Furious',
 'Iron Man 3',
 'Minions',
 'Captain America: Civil War',
 'Aquaman',
 'The Lord of the Rings: The Return of the King',
 'Spider-Man: Far From Home',
 'Captain Marvel',
 'Transformers: Dark of the Moon',
 'Skyfall',
 'Transformers: Age of Extinction',
 'The Dark Knight Rises',
 'Joker',
 'Star Wars: The Rise of Skywalker',
 'Toy Story 4',
 'Toy Story 3',
 "Pirates of the Caribbean: Dead Man's Chest",
 'Moana 2',
 'Rogue One: A Star Wars Story',
 'Aladdin',
 'Star Wars: Episode I – The Phantom Menace',
 'Pirates of the Caribbean: On Stranger Tides',
 'Jurassic Park',
 'Despicable Me 3']

In [36]:
films_df = pd.DataFrame(films, columns = ['Title'],index=range(1,len(films)+1))

In [37]:
# df 1
films_df

                                            Title
1                                          Avatar
2                               Avengers: Endgame
3                        Avatar: The Way of Water
4                                         Titanic
5                                        Ne Zha 2
6                    Star Wars: The Force Awakens
7                          Avengers: Infinity War
8                         Spider-Man: No Way Home
9                                    Inside Out 2
10                                 Jurassic World
11                                  The Lion King
12                                   The Avengers
13                                      Furious 7
14                              Top Gun: Maverick
15                                       Frozen 2
16                                         Barbie
17                        Avengers: Age of Ultron
18                    The Super Mario Bros. Movie
19                                  Black Panther
20  Harry Potter and the Deathly Hallows – Part 2
21                           Deadpool & Wolverine
22                       Star Wars: The Last Jedi
23                 Jurassic World: Fallen Kingdom
24                                         Frozen
25                           Beauty and the Beast
26                                  Incredibles 2
27                        The Fate of the Furious
28                                     Iron Man 3
29                                        Minions
30                     Captain America: Civil War
31                                        Aquaman
32  The Lord of the Rings: The Return of the King
33                      Spider-Man: Far From Home
34                                 Captain Marvel
35                 Transformers: Dark of the Moon
36                                        Skyfall
37                Transformers: Age of Extinction
38                          The Dark Knight Rises
39                                          Joker
40               Star Wars: The Rise of Skywalker
41                                    Toy Story 4
42                                    Toy Story 3
43     Pirates of the Caribbean: Dead Man's Chest
44                                        Moana 2
45                   Rogue One: A Star Wars Story
46                                        Aladdin
47      Star Wars: Episode I – The Phantom Menace
48    Pirates of the Caribbean: On Stranger Tides
49                                  Jurassic Park
50                                Despicable Me 3

In [38]:
# set the API key - set this in an external .env file
key = '99012437c18003a8e7f6b9c063cb749a'

In [39]:
films_information = []
for film in films:
  encoded_film = quote(film)
  # endpoint
  url = f'https://api.themoviedb.org/3/search/movie?api_key={key}&query={encoded_film}'
  # make a request to the endpoint
  r = requests.get(url).json()

  if r['results']:
    first_result = r['results'][0]
    films_information.append({
        'Title': first_result['title'],
        'Original_title': first_result['original_title'],
        'Release_date': first_result['release_date'],
        'Overview': first_result['overview'],
        'Popularity': first_result['popularity'],
        'Vote_count': first_result['vote_count'],
        'Vote_average': first_result['vote_average'],
    })
  else:
    print(f'No results found for {film}')

for film in films_information:
  print(film)

{'Title': 'Avatar', 'Original_title': 'Avatar', 'Release_date': '2009-12-15', 'Overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.', 'Popularity': 25.6993, 'Vote_count': 32470, 'Vote_average': 7.592}
{'Title': 'Avengers: Endgame', 'Original_title': 'Avengers: Endgame', 'Release_date': '2019-04-24', 'Overview': "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.", 'Popularity': 17.2409, 'Vote_count': 26587, 'Vote_average': 8.239}
{'Title': 'Avatar: The Way of Water', 'Original_title': 'Avatar: The Way of Water', 'Release_date': '2022-12-14', 'Overview': 'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.', 'Popularity': 25.9127, 'Vote_count': 12748, 'Vote_average': 7.6}
{'Title': 'Titanic', 'Original_title': 'Titanic', 'Release_date': '1997-11-18', 'Overview': "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.", 'Popularity': 25.1099, 'Vote_count': 26213, 'Vote_average': 7.905}
{'Title': 'Ne Zha 2', 'Original_title': '哪吒之魔童闹海', 'Release_date': '2025-01-29', 'Overview': 'After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.', 'Popularity': 274.277, 'Vote_count': 258, 'Vote_average': 8.019}
{'Title': 'Star Wars: The Force Awakens', 'Original_title': 'Star Wars: The Force Awakens', 'Release_date': '2015-12-15', 'Overview': 'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.', 'Popularity': 9.0643, 'Vote_count': 19882, 'Vote_average': 7.258}
{'Title': 'Avengers: Infinity War', 'Original_title': 'Avengers: Infinity War', 'Release_date': '2018-04-25', 'Overview': 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.', 'Popularity': 30.8328, 'Vote_count': 30806, 'Vote_average': 8.2}
{'Title': 'Spider-Man: No Way Home', 'Original_title': 'Spider-Man: No Way Home', 'Release_date': '2021-12-15', 'Overview': 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', 'Popularity': 30.5849, 'Vote_count': 20974, 'Vote_average': 7.943}
{'Title': 'Inside Out 2', 'Original_title': 'Inside Out 2', 'Release_date': '2024-06-11', 'Overview': "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.", 'Popularity': 35.4515, 'Vote_count': 6039, 'Vote_average': 7.553}
{'Title': 'Jurassic World Rebirth', 'Original_title': 'Jurassic World Rebirth', 'Release_date': '2025-07-01', 'Overview': "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.", 'Popularity': 1127.7172, 'Vote_count': 1370, 'Vote_average': 6.411}
{'Title': 'The Lion King', 'Original_title': 'The Lion King', 'Release_date': '1994-06-15', 'Overview': 'Young lion prince Simba, eager to one day become king of the Pride Lands, grows up under the watchful eye of his father Mufasa; all the while his villainous uncle Scar conspires to take the throne for himself. Amid betrayal and tragedy, Simba must confront his past and find his rightful place in the Circle of Life.', 'Popularity': 16.6694, 'Vote_count': 18921, 'Vote_average': 8.257}
{'Title': 'The Avengers', 'Original_title': 'The Avengers', 'Release_date': '2012-04-25', 'Overview': 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!', 'Popularity': 31.8539, 'Vote_count': 32639, 'Vote_average': 7.786}
{'Title': 'Furious 7', 'Original_title': 'Furious 7', 'Release_date': '2015-04-01', 'Overview': 'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.', 'Popularity': 17.1519, 'Vote_count': 10894, 'Vote_average': 7.223}
{'Title': 'Top Gun: Maverick', 'Original_title': 'Top Gun: Maverick', 'Release_date': '2022-05-21', 'Overview': 'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.', 'Popularity': 21.2637, 'Vote_count': 10075, 'Vote_average': 8.169}
{'Title': 'B-29 Frozen in Time', 'Original_title': 'B-29 Frozen in Time', 'Release_date': '1996-01-30', 'Overview': 'NOVA accompanies famed test pilot Darryl Greenamyer and his intrepid crew on a perilous mission to repair and re-fly a B-29 bomber stranded on the Greenland icecap since 1947. In the face of incredible hardships, the team struggles to bring the old warbird back to life.', 'Popularity': 0.1498, 'Vote_count': 2, 'Vote_average': 6.5}
{'Title': 'Barbie', 'Original_title': 'Barbie', 'Release_date': '2023-06-18', 'Overview': 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.', 'Popularity': 14.9025, 'Vote_count': 10164, 'Vote_average': 6.969}
{'Title': 'Avengers: Age of Ultron', 'Original_title': 'Avengers: Age of Ultron', 'Release_date': '2015-04-22', 'Overview': 'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.', 'Popularity': 14.8979, 'Vote_count': 23614, 'Vote_average': 7.3}
{'Title': 'The Super Mario Bros. Movie', 'Original_title': 'The Super Mario Bros. Movie', 'Release_date': '2023-04-05', 'Overview': 'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.', 'Popularity': 18.5746, 'Vote_count': 9873, 'Vote_average': 7.615}
{'Title': 'Black Panther', 'Original_title': 'Black Panther', 'Release_date': '2018-02-13', 'Overview': "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.", 'Popularity': 11.7335, 'Vote_count': 22719, 'Vote_average': 7.4}
{'Title': 'Harry Potter and the Deathly Hallows: Part 2', 'Original_title': 'Harry Potter and the Deathly Hallows: Part 2', 'Release_date': '2011-07-12', 'Overview': "Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.", 'Popularity': 19.7437, 'Vote_count': 21184, 'Vote_average': 8.086}
{'Title': 'Deadpool & Wolverine', 'Original_title': 'Deadpool & Wolverine', 'Release_date': '2024-07-24', 'Overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.', 'Popularity': 40.3432, 'Vote_count': 7574, 'Vote_average': 7.584}
{'Title': 'Star Wars: The Last Jedi', 'Original_title': 'Star Wars: The Last Jedi', 'Release_date': '2017-12-13', 'Overview': 'Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.', 'Popularity': 9.0535, 'Vote_count': 15732, 'Vote_average': 6.772}
{'Title': 'Jurassic World: Fallen Kingdom', 'Original_title': 'Jurassic World: Fallen Kingdom', 'Release_date': '2018-06-06', 'Overview': "Three years after Jurassic World was destroyed, Isla Nublar now sits abandoned. When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.", 'Popularity': 24.8733, 'Vote_count': 12240, 'Vote_average': 6.54}
{'Title': 'Frozen', 'Original_title': 'Frozen', 'Release_date': '2013-11-20', 'Overview': "Young princess Anna of Arendelle dreams about finding true love at her sister Elsa’s coronation. Fate takes her on a dangerous journey in an attempt to end the eternal winter that has fallen over the kingdom. She's accompanied by ice delivery man Kristoff, his reindeer Sven, and snowman Olaf. On an adventure where she will find out what friendship, courage, family, and true love really means.", 'Popularity': 17.898, 'Vote_count': 16995, 'Vote_average': 7.247}
{'Title': 'Beauty and the Beast', 'Original_title': 'Beauty and the Beast', 'Release_date': '2010-02-11', 'Overview': "A twist on the morality tale of forbidden love between the beautiful Belle and the feared Beast. As the villagers are being brutally murdered and the Beast is hunted down as the one responsible for the mayhem, Belle and Beast team up to defeat the real killer; the power-hungry witch's malevolent troll.", 'Popularity': 1.4193, 'Vote_count': 59, 'Vote_average': 4.263}
{'Title': 'Incredibles 2', 'Original_title': 'Incredibles 2', 'Release_date': '2018-06-14', 'Overview': 'Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.', 'Popularity': 13.8685, 'Vote_count': 13185, 'Vote_average': 7.454}
{'Title': 'The Fate of the Furious', 'Original_title': 'The Fate of the Furious', 'Release_date': '2017-04-12', 'Overview': 'When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.', 'Popularity': 10.4635, 'Vote_count': 10491, 'Vote_average': 6.862}
{'Title': 'Iron Man 3', 'Original_title': 'Iron Man 3', 'Release_date': '2013-04-18', 'Overview': "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.", 'Popularity': 16.6314, 'Vote_count': 22715, 'Vote_average': 6.93}
{'Title': 'Minions', 'Original_title': 'Minions', 'Release_date': '2015-06-17', 'Overview': 'Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.', 'Popularity': 4.1535, 'Vote_count': 10781, 'Vote_average': 6.414}
{'Title': 'Captain America: Civil War', 'Original_title': 'Captain America: Civil War', 'Release_date': '2016-04-27', 'Overview': 'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.', 'Popularity': 16.7952, 'Vote_count': 23301, 'Vote_average': 7.4}
{'Title': 'Aquaman', 'Original_title': 'Aquaman', 'Release_date': '2018-12-07', 'Overview': 'Half-human, half-Atlantean Arthur Curry is taken on the journey of his lifetime to discover if he is worth of being a king.', 'Popularity': 7.2131, 'Vote_count': 14421, 'Vote_average': 6.874}
{'Title': 'The Lord of the Rings: The Return of the King', 'Original_title': 'The Lord of the Rings: The Return of the King', 'Release_date': '2003-12-17', 'Overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b', 'Popularity': 18.1638, 'Vote_count': 25324, 'Vote_average': 8.489}
{'Title': 'Spider-Man: Far From Home', 'Original_title': 'Spider-Man: Far From Home', 'Release_date': '2019-06-28', 'Overview': 'Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.', 'Popularity': 19.9327, 'Vote_count': 16227, 'Vote_average': 7.405}
{'Title': 'Captain Marvel', 'Original_title': 'Captain Marvel', 'Release_date': '2019-03-06', 'Overview': 'The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.', 'Popularity': 8.3449, 'Vote_count': 16185, 'Vote_average': 6.8}
{'Title': 'Transformers: Dark of the Moon', 'Original_title': 'Transformers: Dark of the Moon', 'Release_date': '2011-06-28', 'Overview': 'The Autobots continue to work for NEST, now no longer in secret. But after discovering a strange artifact during a mission in Chernobyl, it becomes apparent to Optimus Prime that the United States government has been less than forthright with them.', 'Popularity': 2.659, 'Vote_count': 8572, 'Vote_average': 6.2}
{'Title': 'Skyfall', 'Original_title': 'Skyfall', 'Release_date': '2012-10-24', 'Overview': "When Bond's latest assignment goes gravely wrong, agents around the world are exposed and MI6 headquarters is attacked. While M faces challenges to her authority and position from Gareth Mallory, the new Chairman of the Intelligence and Security Committee, it's up to Bond, aided only by field agent Eve, to locate the mastermind behind the attack.", 'Popularity': 8.2197, 'Vote_count': 15539, 'Vote_average': 7.251}
{'Title': 'Transformers: Age of Extinction', 'Original_title': 'Transformers: Age of Extinction', 'Release_date': '2014-06-25', 'Overview': 'As humanity picks up the pieces after the battle of Chicago, a shadowy group reveals itself in an attempt to control the direction of history…while an ancient, powerful new menace sets Earth in its crosshairs. With help from Cade Yeager, Optimus Prime and the Autobots rise to meet their most fearsome challenge yet.', 'Popularity': 10.9791, 'Vote_count': 8403, 'Vote_average': 5.949}
{'Title': 'The Dark Knight Rises', 'Original_title': 'The Dark Knight Rises', 'Release_date': '2012-07-17', 'Overview': "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.", 'Popularity': 14.8284, 'Vote_count': 23416, 'Vote_average': 7.787}
{'Title': 'Joker', 'Original_title': 'Joker', 'Release_date': '2019-10-01', 'Overview': 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.', 'Popularity': 14.8488, 'Vote_count': 26663, 'Vote_average': 8.133}
{'Title': 'Star Wars: The Rise of Skywalker', 'Original_title': 'Star Wars: The Rise of Skywalker', 'Release_date': '2019-12-18', 'Overview': 'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.', 'Popularity': 8.3521, 'Vote_count': 10297, 'Vote_average': 6.288}
{'Title': 'Toy Story 4', 'Original_title': 'Toy Story 4', 'Release_date': '2019-06-19', 'Overview': 'Woody has always been confident about his place in the world and that his priority is taking care of his kid, whether that\'s Andy or Bonnie. But when Bonnie adds a reluctant new toy called "Forky" to her room, a road trip adventure alongside old and new friends will show Woody how big the world can be for a toy.', 'Popularity': 9.2891, 'Vote_count': 10098, 'Vote_average': 7.471}
{'Title': 'Toy Story 3', 'Original_title': 'Toy Story 3', 'Release_date': '2010-06-16', 'Overview': "Woody, Buzz, and the rest of Andy's toys haven't been played with in years. With Andy about to go to college, the gang find themselves accidentally left at a nefarious day care center. The toys must band together to escape and return home to Andy.", 'Popularity': 11.0291, 'Vote_count': 15096, 'Vote_average': 7.8}

In [40]:
films_information_df = pd.DataFrame(films_information, index=range(1, len(films_information)+1))

In [41]:
films_information_df

,Title,Original_title,Release_date,Overview,Popularity,Vote_count,Vote_average
1,Avatar,Avatar,2009-12-15,"In the 22nd century, a paraplegic Marine is di...",25.6993,32470,7.592
2,Avengers: Endgame,Avengers: Endgame,2019-04-24,After the devastating events of Avengers: Infi...,17.2409,26587,8.239
3,Avatar: The Way of Water,Avatar: The Way of Water,2022-12-14,Set more than a decade after the events of the...,25.9127,12748,7.600
4,Titanic,Titanic,1997-11-18,101-year-old Rose DeWitt Bukater tells the sto...,25.1099,26213,7.905
5,Ne Zha 2,哪吒之魔童闹海,2025-01-29,After a catastrophic event leaves their bodies...,274.2770,258,8.019
6,Star Wars: The Force Awakens,Star Wars: The Force Awakens,2015-12-15,Thirty years after defeating the Galactic Empi...,9.0643,19882,7.258
7,Avengers: Infinity War,Avengers: Infinity War,2018-04-25,As the Avengers and their allies have continue...,30.8328,30806,8.200
8,Spider-Man: No Way Home,Spider-Man: No Way Home,2021-12-15,Peter Parker is unmasked and no longer able to...,30.5849,20974,7.943
9,Inside Out 2,Inside Out 2,2024-06-11,Teenager Riley's mind headquarters is undergoi...,35.4515,6039,7.553
10,Jurassic World Rebirth,Jurassic World Rebirth,2025-07-01,Five years after the events of Jurassic World ...,1127.7172,1370,6.411
11,The Lion King,The Lion King,1994-06-15,"Young lion prince Simba, eager to one day beco...",16.6694,18921,8.257
12,The Avengers,The Avengers,2012-04-25,When an unexpected enemy emerges and threatens...,31.8539,32639,7.786
13,Furious 7,Furious 7,2015-04-01,Deckard Shaw seeks revenge against Dominic Tor...,17.1519,10894,7.223
14,Top Gun: Maverick,Top Gun: Maverick,2022-05-21,After more than thirty years of service as one...,21.2637,10075,8.169
15,B-29 Frozen in Time,B-29 Frozen in Time,1996-01-30,NOVA accompanies famed test pilot Darryl Green...,0.1498,2,6.500
16,Barbie,Barbie,2023-06-18,Barbie and Ken are having the time of their li...,14.9025,10164,6.969
17,Avengers: Age of Ultron,Avengers: Age of Ultron,2015-04-22,When Tony Stark tries to jumpstart a dormant p...,14.8979,23614,7.300
18,The Super Mario Bros. Movie,The Super Mario Bros. Movie,2023-04-05,"While working underground to fix a water main,...",18.5746,9873,7.615
19,Black Panther,Black Panther,2018-02-13,"King T'Challa returns home to the reclusive, t...",11.7335,22719,7.400
20,Harry Potter and the Deathly Hallows: Part 2,Harry Potter and the Deathly Hallows: Part 2,2011-07-12,"Harry, Ron and Hermione continue their quest t...",19.7437,21184,8.086
21,Deadpool & Wolverine,Deadpool & Wolverine,2024-07-24,A listless Wade Wilson toils away in civilian ...,40.3432,7574,7.584
22,Star Wars: The Last Jedi,Star Wars: The Last Jedi,2017-12-13,Rey develops her newly discovered abilities wi...,9.0535,15732,6.772
23,Jurassic World: Fallen Kingdom,Jurassic World: Fallen Kingdom,2018-06-06,Three years after Jurassic World was destroyed...,24.8733,12240,6.540
24,Frozen,Frozen,2013-11-20,Young princess Anna of Arendelle dreams about ...,17.8980,16995,7.247
25,Beauty and the Beast,Beauty and the Beast,2010-02-11,A twist on the morality tale of forbidden love...,1.4193,59,4.263
26,Incredibles 2,Incredibles 2,2018-06-14,Elastigirl springs into action to save the day...,13.8685,13185,7.454
27,The Fate of the Furious,The Fate of the Furious,2017-04-12,When a mysterious woman seduces Dom into the w...,10.4635,10491,6.862
28,Iron Man 3,Iron Man 3,2013-04-18,When Tony Stark's world is torn apart by a for...,16.6314,22715,6.930
29,Minions,Minions,2015-06-17,"Minions Stuart, Kevin and Bob are recruited by...",4.1535,10781,6.414
30,Captain America: Civil War,Captain America: Civil War,2016-04-27,"Following the events of Age of Ultron, the col...",16.7952,23301,7.400
31,Aquaman,Aquaman,2018-12-07,"Half-human, half-Atlantean Arthur Curry is tak...",7.2131,14421,6.874
32,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,2003-12-17,As armies mass for a final battle that will de...,18.1638,25324,8.489
33,Spider-Man: Far From Home,Spider-Man: Far From Home,2019-06-28,Peter Parker and his friends go on a summer tr...,19.9327,16227,7.405
34,Captain Marvel,Captain Marvel,2019-03-06,The story follows Carol Danvers as she becomes...,8.3449,16185,6.800
35,Transformers: Dark of the Moon,Transformers: Dark of the Moon,2011-06-28,"The Autobots continue to work for NEST, now no...",2.6590,8572,6.200
36,Skyfall,Skyfall,2012-10-24,When Bond's latest assignment goes gravely wro...,8.2197,15539,7.251
37,Transformers: Age of Extinction,Transformers: Age of Extinction,2014-06-25,As humanity picks up the pieces after the batt...,10.9791,8403,5.949
38,The Dark Knight Rises,The Dark Knight Rises,2012-07-17,Following the death of District Attorney Harve...,14.8284,23416,7.787
39,Joker,Joker,2019-10-01,"During the 1980s, a failed stand-up comedian i...",14.8488,26663,8.133
40,Star Wars: The Rise of Skywalker,Star Wars: The Rise of Skywalker,2019-12-18,The surviving Resistance faces the First Order...,8.3521,10297,6.288
41,Toy Story 4,Toy Story 4,2019-06-19,Woody has always been confident about his plac...,9.2891,10098,7.471
42,Toy Story 3,Toy Story 3,2010-06-16,"Woody, Buzz, and the rest of Andy's toys haven...",11.0291,15096,7.800
43,Pirates of the Caribbean: Dead Man's Chest,Pirates of the Caribbean: Dead Man's Chest,2006-07-06,Captain Jack Sparrow races to recover the hear...,16.9343,16492,7.368
44,Moana 2,Moana 2,2024-11-21,After receiving an unexpected call from her wa...,54.2616,2627,7.053
45,Rogue One: A Star Wars Story,Rogue One: A Star Wars Story,2016-12-14,A rogue band of resistance fighters unite for ...,6.9326,15785,7.501
46,Aladdin,Aladdin,2019-05-22,A kindhearted street urchin named Aladdin emba...,8.5989,10298,7.100
47,Star Wars: Episode I - The Phantom Menace,Star Wars: Episode I - The Phantom Menace,1999-05-19,"Anakin Skywalker, a young slave strong with th...",7.6589,15148,6.564
48,Pirates of the Caribbean: On Stranger Tides,Pirates of the Caribbean: On Stranger Tides,2011-05-15,Captain Jack Sparrow crosses paths with a woma...,14.7068,14415,6.562
49,Jurassic Park,Jurassic Park,1993-06-11,A wealthy entrepreneur secretly creates a them...,15.4461,16998,7.959
50,Despicable Me 3,Despicable Me 3,2017-06-15,Gru and his wife Lucy must stop former '80s ch...,6.5749,7362,6.467

In [42]:

merged_df = pd.merge(films_df, films_information_df, on = 'Title', how = 'right')

In [43]:
merged_df

,Title,Original_title,Release_date,Overview,Popularity,Vote_count,Vote_average
0,Avatar,Avatar,2009-12-15,"In the 22nd century, a paraplegic Marine is di...",25.6993,32470,7.592
1,Avengers: Endgame,Avengers: Endgame,2019-04-24,After the devastating events of Avengers: Infi...,17.2409,26587,8.239
2,Avatar: The Way of Water,Avatar: The Way of Water,2022-12-14,Set more than a decade after the events of the...,25.9127,12748,7.600
3,Titanic,Titanic,1997-11-18,101-year-old Rose DeWitt Bukater tells the sto...,25.1099,26213,7.905
4,Ne Zha 2,哪吒之魔童闹海,2025-01-29,After a catastrophic event leaves their bodies...,274.2770,258,8.019
5,Star Wars: The Force Awakens,Star Wars: The Force Awakens,2015-12-15,Thirty years after defeating the Galactic Empi...,9.0643,19882,7.258
6,Avengers: Infinity War,Avengers: Infinity War,2018-04-25,As the Avengers and their allies have continue...,30.8328,30806,8.200
7,Spider-Man: No Way Home,Spider-Man: No Way Home,2021-12-15,Peter Parker is unmasked and no longer able to...,30.5849,20974,7.943
8,Inside Out 2,Inside Out 2,2024-06-11,Teenager Riley's mind headquarters is undergoi...,35.4515,6039,7.553
9,Jurassic World Rebirth,Jurassic World Rebirth,2025-07-01,Five years after the events of Jurassic World ...,1127.7172,1370,6.411
10,The Lion King,The Lion King,1994-06-15,"Young lion prince Simba, eager to one day beco...",16.6694,18921,8.257
11,The Avengers,The Avengers,2012-04-25,When an unexpected enemy emerges and threatens...,31.8539,32639,7.786
12,Furious 7,Furious 7,2015-04-01,Deckard Shaw seeks revenge against Dominic Tor...,17.1519,10894,7.223
13,Top Gun: Maverick,Top Gun: Maverick,2022-05-21,After more than thirty years of service as one...,21.2637,10075,8.169
14,B-29 Frozen in Time,B-29 Frozen in Time,1996-01-30,NOVA accompanies famed test pilot Darryl Green...,0.1498,2,6.500
15,Barbie,Barbie,2023-06-18,Barbie and Ken are having the time of their li...,14.9025,10164,6.969
16,Avengers: Age of Ultron,Avengers: Age of Ultron,2015-04-22,When Tony Stark tries to jumpstart a dormant p...,14.8979,23614,7.300
17,The Super Mario Bros. Movie,The Super Mario Bros. Movie,2023-04-05,"While working underground to fix a water main,...",18.5746,9873,7.615
18,Black Panther,Black Panther,2018-02-13,"King T'Challa returns home to the reclusive, t...",11.7335,22719,7.400
19,Harry Potter and the Deathly Hallows: Part 2,Harry Potter and the Deathly Hallows: Part 2,2011-07-12,"Harry, Ron and Hermione continue their quest t...",19.7437,21184,8.086
20,Deadpool & Wolverine,Deadpool & Wolverine,2024-07-24,A listless Wade Wilson toils away in civilian ...,40.3432,7574,7.584
21,Star Wars: The Last Jedi,Star Wars: The Last Jedi,2017-12-13,Rey develops her newly discovered abilities wi...,9.0535,15732,6.772
22,Jurassic World: Fallen Kingdom,Jurassic World: Fallen Kingdom,2018-06-06,Three years after Jurassic World was destroyed...,24.8733,12240,6.540
23,Frozen,Frozen,2013-11-20,Young princess Anna of Arendelle dreams about ...,17.8980,16995,7.247
24,Beauty and the Beast,Beauty and the Beast,2010-02-11,A twist on the morality tale of forbidden love...,1.4193,59,4.263
25,Incredibles 2,Incredibles 2,2018-06-14,Elastigirl springs into action to save the day...,13.8685,13185,7.454
26,The Fate of the Furious,The Fate of the Furious,2017-04-12,When a mysterious woman seduces Dom into the w...,10.4635,10491,6.862
27,Iron Man 3,Iron Man 3,2013-04-18,When Tony Stark's world is torn apart by a for...,16.6314,22715,6.930
28,Minions,Minions,2015-06-17,"Minions Stuart, Kevin and Bob are recruited by...",4.1535,10781,6.414
29,Captain America: Civil War,Captain America: Civil War,2016-04-27,"Following the events of Age of Ultron, the col...",16.7952,23301,7.400
30,Aquaman,Aquaman,2018-12-07,"Half-human, half-Atlantean Arthur Curry is tak...",7.2131,14421,6.874
31,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,2003-12-17,As armies mass for a final battle that will de...,18.1638,25324,8.489
32,Spider-Man: Far From Home,Spider-Man: Far From Home,2019-06-28,Peter Parker and his friends go on a summer tr...,19.9327,16227,7.405
33,Captain Marvel,Captain Marvel,2019-03-06,The story follows Carol Danvers as she becomes...,8.3449,16185,6.800
34,Transformers: Dark of the Moon,Transformers: Dark of the Moon,2011-06-28,"The Autobots continue to work for NEST, now no...",2.6590,8572,6.200
35,Skyfall,Skyfall,2012-10-24,When Bond's latest assignment goes gravely wro...,8.2197,15539,7.251
36,Transformers: Age of Extinction,Transformers: Age of Extinction,2014-06-25,As humanity picks up the pieces after the batt...,10.9791,8403,5.949
37,The Dark Knight Rises,The Dark Knight Rises,2012-07-17,Following the death of District Attorney Harve...,14.8284,23416,7.787
38,Joker,Joker,2019-10-01,"During the 1980s, a failed stand-up comedian i...",14.8488,26663,8.133
39,Star Wars: The Rise of Skywalker,Star Wars: The Rise of Skywalker,2019-12-18,The surviving Resistance faces the First Order...,8.3521,10297,6.288
40,Toy Story 4,Toy Story 4,2019-06-19,Woody has always been confident about his plac...,9.2891,10098,7.471
41,Toy Story 3,Toy Story 3,2010-06-16,"Woody, Buzz, and the rest of Andy's toys haven...",11.0291,15096,7.800
42,Pirates of the Caribbean: Dead Man's Chest,Pirates of the Caribbean: Dead Man's Chest,2006-07-06,Captain Jack Sparrow races to recover the hear...,16.9343,16492,7.368
43,Moana 2,Moana 2,2024-11-21,After receiving an unexpected call from her wa...,54.2616,2627,7.053
44,Rogue One: A Star Wars Story,Rogue One: A Star Wars Story,2016-12-14,A rogue band of resistance fighters unite for ...,6.9326,15785,7.501
45,Aladdin,Aladdin,2019-05-22,A kindhearted street urchin named Aladdin emba...,8.5989,10298,7.100
46,Star Wars: Episode I - The Phantom Menace,Star Wars: Episode I - The Phantom Menace,1999-05-19,"Anakin Skywalker, a young slave strong with th...",7.6589,15148,6.564
47,Pirates of the Caribbean: On Stranger Tides,Pirates of the Caribbean: On Stranger Tides,2011-05-15,Captain Jack Sparrow crosses paths with a woma...,14.7068,14415,6.562
48,Jurassic Park,Jurassic Park,1993-06-11,A wealthy entrepreneur secretly creates a them...,15.4461,16998,7.959
49,Despicable Me 3,Despicable Me 3,2017-06-15,Gru and his wife Lucy must stop former '80s ch...,6.5749,7362,6.467

In [44]:
merged_df.to_csv('Top Gross-Profit movies.csv', index = False)

In [45]:
df = pd.read_csv('Top Gross-Profit movies.csv')

In [46]:
df.describe()

        Popularity    Vote_count  Vote_average
count    50.000000     50.000000     50.000000
mean     43.786094  15197.420000      7.250240
std     160.938152   8236.808541      0.757074
min       0.149800      2.000000      4.263000
25%       9.056200  10114.500000      6.815500
50%      15.174300  15122.000000      7.384000
75%      20.930950  21131.500000      7.786750
max    1127.717200  32639.000000      8.489000